# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Required: the build image and the Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Install the MkDocs version that the site is built with
python:
  install:
    - requirements: Docs/requirements.txt
